name: dev3d
channels:
  - pytorch
  - comet_ml
  - conda-forge
  - defaults
dependencies:
  - autopep8
  - comet_ml
  - tensorboard
  - cudatoolkit=11.6.0
  - debugpy
  - eigen
  - einops
  - h5py
  - hdf4
  - hdf5
  - notebook
  - ipycanvas
  - ipyevents
  - ipygany
  - ipykernel
  - ipython
  - ipython_genutils
  - ipyvtklink
  - ipywidgets
  - matplotlib
  - nibabel
  - numpy
  - opencv=4.7.0
  - pandas
  - panel
  - pillow
  - pip
  - pydicom
  - dicom2nifti
  - pynrrd
  - python>=3.9
  - pytorch=1.12.1=py3.9_cuda11.6_cudnn8.3.2_0
  - pyvista
  - libgcc
  - scikit-image
  - scikit-learn
  - scipy
  - torchvision=0.13.1=py39_cu116
  - tqdm
  - vtk
  - wheel
  - xvfbwrapper
  - yaml
  - pip:
      - natsort==8.2.0
      - torch-tb-profiler
